In [2]:
#initalisation 
import findspark 
findspark.init()
import pyspark
from pyspark import SparkConf, SparkContext

spark_conf = SparkConf().setMaster("local[*]").setAppName("task2")
sc = SparkContext(conf = spark_conf)
sc

In [3]:
from pyspark.sql import SparkSession

In [4]:
spark = SparkSession.builder.master("local[*]").appName("task").getOrCreate()

In [5]:
file = spark.read.csv("D:\spark-and-stuff\Assignment_Dataframes\Movies.csv.csv",inferSchema=True,header=True)

In [6]:
file.printSchema

In [7]:
file.describe()

DataFrame[summary: string, Year: string, Length: string, Title: string, Genre: string, Actor: string, Actress: string, Director: string, Popularity: string, Awards: string, Image: string]

In [8]:
file.show(1)

+----+------+--------------------+------+---------------+-------------+--------------+----------+------+----------------+
|Year|Length|               Title| Genre|          Actor|      Actress|      Director|Popularity|Awards|           Image|
+----+------+--------------------+------+---------------+-------------+--------------+----------+------+----------------+
|1990|   111|Tie Me Up! Tie Me...|Comedy|BanderasAntonio|AbrilVictoria|Almod√≥varPedro|        68|    No|NicholasCage.png|
+----+------+--------------------+------+---------------+-------------+--------------+----------+------+----------------+
only showing top 1 row

# q1

In [9]:
df_1 = file.filter((file.Awards == "Yes") & (file.Genre == "Action")).select('Title','Year','Director').show()

+-----+----+--------+
|Title|Year|Director|
+-----+----+--------+
+-----+----+--------+

# q2

In [10]:
df_2_1 = file.filter(file.Awards == "Yes")

In [11]:
df_2_1.groupBy('Actor')

In [12]:
df_2_1.select('Title','Director').show()

+--------------------+-------------------+
|               Title|           Director|
+--------------------+-------------------+
| Fanny and Alexander|      BergmanIngmar|
|     A Man & a Woman|      LelouchClaude|
|Un Hombre y una M...|      LelouchClaude|
|   Official StoryThe|         PuenzoLuiz|
|   Wild Strawberries|      BergmanIngmar|
|Through a Glass D...|      BergmanIngmar|
|    Cries & Whispers|      BergmanIngmar|
|   Sound of MusicThe|         WiseRobert|
|     Babette's Feast|        AxelGabriel|
|Murder on the Ori...|        LumetSidney|
|     Elephant ManThe|         LynchDavid|
|E. T. The Extra-T...|    SpielbergSteven|
|              Misery|          ReinerRob|
|              Gandhi|AttenboroughRichard|
|       Autumn Sonata|      BergmanIngmar|
|            Gaslight|        CukorGeorge|
|A Woman Called Golda|         GibsonAlan|
|           Anastasia|      LitvakAnatole|
|       Cactus Flower|           SaksGene|
|             Amadeus|        FormanMilos|
+--------------------+-------------------+
only showing top 20 rows

# q3

In [13]:
df_3_1 = file.filter(file.Awards == 'No').sort(file.Popularity .desc()).show(10)

+----+------+-------------------+---------------+---------------+--------------+--------------------+----------+------+----------------+
|Year|Length|              Title|          Genre|          Actor|       Actress|            Director|Popularity|Awards|           Image|
+----+------+-------------------+---------------+---------------+--------------+--------------------+----------+------+----------------+
|1989|    86|        Let It Ride|         Comedy|DreyfussRichard|      GarrTeri|            PytkaJoe|        88|    No|NicholasCage.png|
|1991|   160|      Great RaceThe|         Comedy|    MooreDudley|   WoodNatalie|        EdwardsBlake|        88|    No|NicholasCage.png|
|1989|    90|     New Year's Day|         Comedy|    JaglomHenry|JakobsenMaggie|         JaglomHenry|        88|    No|NicholasCage.png|
|1989|    88|       Final Notice|        Mystery|      GerardGil|AndersonMelody|SternSteven Hilliard|        88|    No|NicholasCage.png|
|1970|   130|  Fellini Satyricon|          Drama|   PotterMartin|   KellerHiram|     FelliniFederico|        88|    No|NicholasCage.png|
|1990|   105|Guilty by Suspicion|          Drama|  De NiroRobert| BeningAnnette|        WinklerIrwin|        88|    No|NicholasCage.png|
|1960|   103|    Time MachineThe|Science Fiction|      TaylorRod| MimieuxYvette|           PalGeorge|        88|    No|NicholasCage.png|
|1991|    91|          Raw Nerve|        Mystery|      FordGlenn|BergmanSandahl|       PriorDavid A.|        88|    No|   glennFord.png|
|1940|   105|Long Voyage HomeThe|          Drama|      WayneJohn|NatwickMildred|            FordJohn|        88|    No|   johnWayne.png|
|1992|   100|          Class Act|          Drama|ReidChristopher|   PerlmanRhea|                null|        88|    No|NicholasCage.png|
+----+------+-------------------+---------------+---------------+--------------+--------------------+----------+------+----------------+
only showing top 10 rows

# q4

In [1]:
df_4_1 = file.filter((file.Year <= '1980') & (file.Popilarity < '20')).sort(file.Popularity.asc()).show(10)

NameError: name 'file' is not defined

# q5

In [15]:
 df_5_1 = file.select('Length', 'Genre')

In [16]:
df_5_2 = df_5_1.groupBy('Genre').max()

In [17]:
df_5_2.show()

+---------------+-----------+
|          Genre|max(Length)|
+---------------+-----------+
|          Crime|         66|
|        Romance|        127|
|      Adventure|        124|
|           null|        180|
|          Drama|        450|
|            War|        183|
|        Fantasy|        102|
|        Mystery|        265|
|          Music|        286|
|Science Fiction|        139|
|         Horror|        144|
|          Short|         40|
|        Western|        298|
|         Comedy|        160|
|         Action|        226|
|       Westerns|        163|
+---------------+-----------+

# q6

In [10]:
from pyspark.sql.functions import sum,avg,max,count

In [12]:
df_6_1 = file.select(['Actor','Actress','Genre']).filter(file.Genre == 'Comedy').groupBy('Actor','Actress').agg(count('Genre').alias('Count'))

In [13]:
df_6_1.filter(df_6_1.Count >= 3).show()

+-------------+----------------+-----+
|        Actor|         Actress|Count|
+-------------+----------------+-----+
|   PiscopoJoe|            null|    3|
|ChapmanGraham|            null|    6|
| TracySpencer|HepburnKatharine|    6|
|  MurphyEddie|            null|    4|
|   CleeseJohn|            null|    4|
| SellersPeter|            null|   11|
|   AllenWoody|     KeatonDiane|    5|
|  MartinSteve|            null|    4|
|WilliamsRobin|            null|    5|
+-------------+----------------+-----+

# q7

In [59]:
df_7_1 = file.select('Actor','Genre').filter((file.Genre == 'Comedy') & (file.Genre == 'Drama')).groupBy('Actor').count().show()

+-----+-----+
|Actor|count|
+-----+-----+
+-----+-----+

# q8

In [15]:
df_8_1 = file.select('Actor','Genre').filter((file.Genre == 'Comedy')|(file.Genre == 'Drama')).groupBy('Actor').count().show()

+---------------+-----+
|          Actor|count|
+---------------+-----+
|     Bos√©Miguel|    1|
|   CottenJoseph|    2|
|     DillonMatt|    2|
|  KeatonMichael|    1|
| ShimuraTakashi|    1|
|   LintDerek De|    1|
|    WillisBruce|    3|
|  LancasterBurt|   14|
|    RomeroCesar|    1|
|   JourdanLouis|    1|
|  ModineMatthew|    1|
|    JaglomHenry|    1|
|       DavisGuy|    1|
|    BridgesBeau|    1|
|    BakulaScott|    1|
|    DoranJohnny|    1|
|CapolicchioLino|    1|
|     FondaPeter|    2|
|       LeeKarla|    1|
| TownsendRobert|    1|
+---------------+-----+
only showing top 20 rows

# q9

In [20]:
df_9_1 = file.select('Actor','Genre').filter((file.Genre != 'Comedy')).groupBy('Actor').count().show()

+---------------+-----+
|          Actor|count|
+---------------+-----+
|   CottenJoseph|    3|
|       BrownTom|    1|
|     DillonMatt|    2|
| ShimuraTakashi|    1|
|   LintDerek De|    1|
|  LancasterBurt|   24|
|    WillisBruce|    2|
|    RomeroCesar|    1|
|  StockwellDean|    1|
|  ModineMatthew|    1|
|    UrichRobert|    1|
|       DavisGuy|    1|
|    BridgesBeau|    1|
|    KattWilliam|    1|
|  EnglundRobert|    1|
|      PriceMarc|    1|
|CapolicchioLino|    1|
|     FondaPeter|    2|
| TownsendRobert|    1|
|  ChesneyArthur|    1|
+---------------+-----+
only showing top 20 rows

# q10

In [26]:
from pyspark.sql.functions import sum,avg,max,count,min

In [27]:
df_10_1 = file.select('Actor','Popularity').groupBy('Actor').agg(max('Popularity').alias('Max'),min('Popularity').alias('Min'),avg('Popularity').alias('Avg')).show()

+--------------+---+---+------------------+
|         Actor|Max|Min|               Avg|
+--------------+---+---+------------------+
|    Bos√©Miguel| 68| 68|              68.0|
|  CottenJoseph| 74| 32|              58.0|
|      BrownTom| 77| 77|              77.0|
|    DillonMatt| 11|  4|               7.5|
| KeatonMichael| 59| 59|              59.0|
|ShimuraTakashi| 36| 36|              36.0|
|  LintDerek De| 71| 71|              71.0|
|   WillisBruce| 76|  7|              48.0|
| LancasterBurt| 84|  0|40.291666666666664|
|   RomeroCesar| 78| 78|              78.0|
| StockwellDean| 70| 70|              70.0|
|  JourdanLouis| 70| 70|              70.0|
| ModineMatthew| 45|  8|              26.5|
|   UrichRobert| 64| 64|              64.0|
|   JaglomHenry| 88| 88|              88.0|
|      DavisGuy| 72| 72|              72.0|
|   BridgesBeau| 64| 64|              64.0|
|   KattWilliam| 26| 26|              26.0|
|   BakulaScott| 60| 60|              60.0|
| EnglundRobert| 41| 41|              41.0|
+--------------+---+---+------------------+
only showing top 20 rows

# q11

In [36]:
df11 = file.select('Year')

In [52]:
y20s = print('count for 20s is: ',file.filter((file.Year < 1929 )& (file.Year > 1920)).count())
y30s = print('count for 30s is: ',file.filter((file.Year < 1939 )& (file.Year > 1930)).count())
y40s = print('count for 40s is: ',file.filter((file.Year < 1949 )& (file.Year > 1940)).count())
y50s = print('count for 50s is: ',file.filter((file.Year < 1959 )& (file.Year > 1950)).count())
y60s = print('count for 60s is: ',file.filter((file.Year < 1969 )& (file.Year > 1960)).count())
y70s = print('count for 70s is: ',file.filter((file.Year < 1979 )& (file.Year > 1970)).count())
y80s = print('count for 80s is: ',file.filter((file.Year < 1989 )& (file.Year > 1980)).count())
y90s = print('count for 90s is: ',file.filter((file.Year < 1999 )& (file.Year > 1990)).count())

count for 20s is:  17
count for 30s is:  55
count for 40s is:  64
count for 50s is:  107
count for 60s is:  124
count for 70s is:  183
count for 80s is:  476
count for 90s is:  240

# q12

In [10]:
df_12_1 = file.groupBy('Year').count().show()

+----+-----+
|Year|count|
+----+-----+
|1959|    9|
|1990|  105|
|1975|   23|
|1977|   29|
|1924|    3|
|1974|   23|
|1927|    3|
|1955|   20|
|1978|   18|
|1925|    1|
|1961|   14|
|1942|    6|
|1944|    4|
|1939|   11|
|1952|   10|
|1956|   15|
|1934|    4|
|1988|   96|
|1997|    1|
|1968|   20|
+----+-----+
only showing top 20 rows

# q13

In [12]:
df_13_1 = file.select('Year','Genre','Length').filter(file.Length > 100).groupBy('Year','Genre').count().show()

+----+---------------+-----+
|Year|          Genre|count|
+----+---------------+-----+
|1989|         Action|   10|
|1988|         Comedy|   10|
|1966|          Drama|    6|
|1985|         Comedy|    6|
|1957|        Western|    1|
|1928|          Drama|    2|
|1970|        Western|    2|
|1975|          Drama|    5|
|1969|         Action|    1|
|1940|         Action|    1|
|1939|        Western|    3|
|1987|         Comedy|   13|
|1982|Science Fiction|    1|
|1951|            War|    1|
|1965|          Music|    1|
|1939|         Comedy|    1|
|1964|          Music|    1|
|1987|            War|    1|
|1962|         Action|    1|
|1966|        Mystery|    3|
+----+---------------+-----+
only showing top 20 rows

# q14

In [14]:
df_14_1 = file.select('Title','Year').filter(file.Year < 1990).sort(file.Title).show()

+--------------------+----+
|               Title|Year|
+--------------------+----+
|2001: A Space Ody...|1968|
|             48 Hrs.|1982|
|               8 1/2|1963|
|A Big Hand for th...|1966|
|  A Child Is Waiting|1962|
|A Chorus LineThe ...|1985|
|  A Clockwork Orange|1971|
|A Coeur Joie(Head...|1967|
|   A Cry in the Dark|1988|
|  A Dry White Season|1989|
|      A Fine Madness|1966|
| A Fish Called Wanda|1988|
|A Fistful of Dollars|1964|
|     A Guy Named Joe|1943|
|    A Lesson in Love|1954|
|A Little Night Music|1977|
|     A Man & a Woman|1966|
|A Man & a Woman: ...|1986|
|A Man for All Sea...|1966|
|    A Matter of Time|1976|
+--------------------+----+
only showing top 20 rows

# q15

In [9]:
df_15_1 = file.select('Title')

In [10]:
rdd=df_15_1.rdd

In [11]:
rdd.collect()

[Row(Title='Tie Me Up! Tie Me Down!'),
 Row(Title='High Heels'),
 Row(Title='Dead ZoneThe'),
 Row(Title='Cuba'),
 Row(Title='Days of Heaven'),
 Row(Title='Octopussy'),
 Row(Title='Target Eagle'),
 Row(Title='American Angels: Baptism of BloodThe'),
 Row(Title='Subway'),
 Row(Title='Camille Claudel'),
 Row(Title='Fanny and Alexander'),
 Row(Title='Tragedy of a Ridiculous Man'),
 Row(Title='A Man & a Woman'),
 Row(Title='A Man & a Woman: Twenty Years Later'),
 Row(Title='Un Hombre y una Mujer'),
 Row(Title='Official StoryThe'),
 Row(Title='Lindbergh Kidnapping CaseThe'),
 Row(Title='Blackmail'),
 Row(Title="Donovan's Reef"),
 Row(Title='Tucker: The Man & His Dream'),
 Row(Title='Scrooged'),
 Row(Title='Raiders of the Lost Ark'),
 Row(Title='Running ManThe'),
 Row(Title='Predator 2'),
 Row(Title='Colors'),
 Row(Title='Zandalee'),
 Row(Title='Miles from Home'),
 Row(Title='Happy Birthday to Me'),
 Row(Title='Final Notice'),
 Row(Title='Quintet'),
 Row(Title="Devil's EyeThe"),
 Row(Title='Wild Strawberries'),
 Row(Title='Seventh SealThe'),
 Row(Title='Germicide'),
 Row(Title='Dreams'),
 Row(Title='Naked NightThe'),
 Row(Title='Through a Glass Darkly'),
 Row(Title='Cries & Whispers'),
 Row(Title='Barbarian & the GeishaThe'),
 Row(Title='Casino Royale'),
 Row(Title='Dr. No'),
 Row(Title='Elephant Walk'),
 Row(Title='Ten'),
 Row(Title='Man Who Loved WomenThe'),
 Row(Title='Hawaii'),
 Row(Title='Torn Curtain'),
 Row(Title='Duet for One'),
 Row(Title='Sound of MusicThe'),
 Row(Title='Gonzo Presents Muppet Weird Stuff'),
 Row(Title='Tartuffe'),
 Row(Title='A New Life'),
 Row(Title='Magic'),
 Row(Title='Tommy'),
 Row(Title='Big FixThe'),
 Row(Title='Alan & Naomi'),
 Row(Title='Fatal Attraction'),
 Row(Title='Patriot Games'),
 Row(Title='Woman Next DoorThe'),
 Row(Title='Hunting'),
 Row(Title='Bataan'),
 Row(Title='SiegfriedThe Nibelungenlied'),
 Row(Title='HenryPortrait of a Serial Killer'),
 Row(Title='Big BlueThe'),
 Row(Title='Flight of the Intruder'),
 Row(Title="Nobody's Fool"),
 Row(Title='After Hours'),
 Row(Title='Desperately Seeking Susan'),
 Row(Title='A New Leaf'),
 Row(Title='Killers of Kilimanjaro'),
 Row(Title='Don Juan'),
 Row(Title="Babette's Feast"),
 Row(Title='VincentFrancoisPaul & the Others'),
 Row(Title='Thunderball'),
 Row(Title='Lodger (Story of the London Fog)'),
 Row(Title='Appointment with Death'),
 Row(Title='Murder on the Orient Express'),
 Row(Title='Blood Alley'),
 Row(Title='Spy Who Loved MeThe'),
 Row(Title='Storm'),
 Row(Title='Bloodbath'),
 Row(Title='Miami Cops'),
 Row(Title='Island of Dr. MoreauThe'),
 Row(Title='Eighty-Four Charing Cross Road'),
 Row(Title='Elephant ManThe'),
 Row(Title='Dr Alien'),
 Row(Title='Creepshow'),
 Row(Title='Sammy & Rosie Get Laid'),
 Row(Title="Goalie's Anxiety at the Penalty KickThe"),
 Row(Title='Mademoiselle Striptease'),
 Row(Title='WomenThe'),
 Row(Title='That Naughty Girl'),
 Row(Title='Voulez-Vous Danser Avec Moi?'),
 Row(Title='A Coeur Joie(Head Over Heels)'),
 Row(Title='Shalako'),
 Row(Title='Contempt'),
 Row(Title='Dear Brigitte'),
 Row(Title='A Very Private Affair'),
 Row(Title='Ravishing IdiotThe'),
 Row(Title='Bride Is Much Too BeautifulThe'),
 Row(Title='Doctor at Sea'),
 Row(Title="Le Repos Du Guerrier(Warrior's Rest)"),
 Row(Title='And God Created Woman'),
 Row(Title='Ms. Don Juan'),
 Row(Title='Siesta'),
 Row(Title='Rich & Strange'),
 Row(Title='Lionheart'),
 Row(Title='E. T. The Extra-Terrestrial'),
 Row(Title='Cool World'),
 Row(Title='Nadine'),
 Row(Title='Batman'),
 Row(Title='Blind Date'),
 Row(Title='Mother Lode'),
 Row(Title='Final Analysis'),
 Row(Title='Never Say Never Again'),
 Row(Title='Nine & a Half Weeks'),
 Row(Title='Killjoy'),
 Row(Title='No Mercy'),
 Row(Title='Marrying ManThe'),
 Row(Title='Misery'),
 Row(Title='Crisis'),
 Row(Title='Samson & Delilah'),
 Row(Title='Act of Piracy'),
 Row(Title='Split Decisions'),
 Row(Title="Vampire's Kiss"),
 Row(Title='Nightmare at Noon'),
 Row(Title='Presumed Innocent'),
 Row(Title='Reap the Wild Wind'),
 Row(Title='Pocket Money'),
 Row(Title='Mary White'),
 Row(Title='Catch a Rising StarTenth Anniversary'),
 Row(Title='Guilty by Suspicion'),
 Row(Title='Secret Beyond the Door'),
 Row(Title='Scarlet Street'),
 Row(Title="Daffy Duck's Quackbusters"),
 Row(Title="Rowlf's Rhapsodies with the Muppets"),
 Row(Title='Gandhi'),
 Row(Title='Wind & the LionThe'),
 Row(Title='Carnal Knowledge'),
 Row(Title='Getting Straight'),
 Row(Title='Scarlet LetterThe'),
 Row(Title='Count of Old TownThe'),
 Row(Title='Autumn Sonata'),
 Row(Title='Gaslight'),
 Row(Title='Indiscreet'),
 Row(Title='Walpurgis Night'),
 Row(Title='Joan of Arc'),
 Row(Title='A Woman Called Golda'),
 Row(Title='A Walk in the Spring Rain'),
 Row(Title='Under Capricorn'),
 Row(Title='Notorious'),
 Row(Title='June Night'),
 Row(Title='Goodbye Again'),
 Row(Title='Anastasia'),
 Row(Title="Bells of St. Mary'sThe"),
 Row(Title='Intermezzo'),
 Row(Title="A Woman's Face"),
 Row(Title='Swedenhielms'),
 Row(Title='Only One Night'),
 Row(Title='Dollar'),
 Row(Title='Elena & Her Men'),
 Row(Title='Europa Fifty-One'),
 Row(Title='Voyage in Italy'),
 Row(Title='Fear'),
 Row(Title='Stromboli'),
 Row(Title='Cactus Flower'),
 Row(Title='Hideaways'),
 Row(Title="Twenty Four Hours in a Woman's Life"),
 Row(Title='Programmed to Kill'),
 Row(Title='Conan the Barbarian'),
 Row(Title='Raw Nerve'),
 Row(Title='Think Dirty'),
 Row(Title='King of Comedy'),
 Row(Title='Best of the Big Laff OffThe'),
 Row(Title='Amadeus'),
 Row(Title='White Lightning'),
 Row(Title='Unbearable Lightness of BeingThe'),
 Row(Title='Life & Times of Judge Roy BeanThe'),
 Row(Title='Airport'),
 Row(Title='Day for Night'),
 Row(Title='Secrets of Women'),
 Row(Title='Burnt Offerings'),
 Row(Title='Easy Rider'),
 Row(Title='Five Easy Pieces'),
 Row(Title='Day of the LocustThe'),
 Row(Title='Goldfinger'),
 Row(Title='Exorcist IIThe Heretic'),
 Row(Title='White Lightning'),
 Row(Title='Lady for a Night'),
 Row(Title='Charly'),
 Row(Title='High Plains Drifter'),
 Row(Title='Honkytonk Man'),
 Row(Title='Nightbreed'),
 Row(Title='Under the Sun of Satan'),
 Row(Title='Vagabond'),
 Row(Title="Bill CosbyLive at Harrah's"),
 Row(Title='Monty Python & the Holy Grail'),
 Row(Title='John Cleese on How to Irritate People'),
 Row(Title='MatchmakerThe'),
 Row(Title='For Your Eyes Only'),
 Row(Title='Wings'),
 Row(Title='Medicine Man'),
 Row(Title='Good Fellas'),
 Row(Title='Kiss of the Spider Woman'),
 Row(Title='RookieTHe'),
 Row(Title='StingThe'),
 Row(Title='Torpedo Run'),
 Row(Title='Instant Justice'),
 Row(Title='Cyrano de Bergerac'),
 Row(Title='Border Street'),
 Row(Title='Firehouse'),
 Row(Title='Morituri'),
 Row(Title='From the Life of the Marionettes'),
 Row(Title='Frantic'),
 Row(Title='Coma'),
 Row(Title='Dead Ringers'),
 Row(Title='Golden Ninja Invasion'),
 Row(Title='ExorcistThe'),
 Row(Title="Alice Doesn't Live Here Anymore"),
 Row(Title='Eyes of the AmaryllisThe'),
 Row(Title='What Price Glory?'),
 Row(Title='Inauguration of the Pleasure Dome'),
 Row(Title='School Daze'),
 Row(Title='End of InnocenceThe'),
 Row(Title='Anderson TapesThe'),
 Row(Title='Father MurphyA Horse from Heaven'),
 Row(Title='Skull'),
 Row(Title='Quick & The DeadThe'),
 Row(Title='Best Defense'),
 Row(Title='Dreamscape'),
 Row(Title='Black Rain'),
 Row(Title='8 1/2'),
 Row(Title='One Frightened Night'),
 Row(Title='Year My Voice BrokeThe'),
 Row(Title='Is Paris Burning?'),
 Row(Title='QB VII'),
 Row(Title='Island of Dr. MoreauThe'),
 Row(Title='Beyond the Limit'),
 Row(Title='Secret Agent'),
 Row(Title='Paramount Comedy Theater: Well-Developed'),
 Row(Title='Big Bust OutThe'),
 Row(Title='Fourth ProtocolThe'),
 Row(Title='Gremlins 2: The New Batch'),
 Row(Title='Fast Times at Ridgemont High'),
 Row(Title='Mannequin'),
 Row(Title='Rabid'),
 Row(Title='PartyThe'),
 Row(Title='Vampire RaidersNinja Queen'),
 Row(Title='Bloopers from Star Trek'),
 Row(Title='Destroyer'),
 Row(Title='Party Girl'),
 Row(Title='Twin Peaks'),
 Row(Title='Moonstruck'),
 Row(Title='Witches of EastwickThe'),
 Row(Title='Moonraker'),
 Row(Title='Beat Street'),
 Row(Title='Running Out of Luck'),
 Row(Title='Never on Tuesday'),
 Row(Title='Shampoo'),
 Row(Title='Power'),
 Row(Title='Darling'),
 Row(Title='Ugly AmericanThe'),
 Row(Title='Ambassador Bill'),
 Row(Title='Big TrailThe'),
 Row(Title='Hombre'),
 Row(Title="Coogan's Bluff"),
 Row(Title='Penn & Teller Get Killed'),
 Row(Title='Shy People'),
 Row(Title="It's My Turn"),
 Row(Title='Dangerous Liaisons'),
 Row(Title='Reversal of Fortune'),
 Row(Title='Meeting Venus'),
 Row(Title='Tomorrow Is Forever'),
 Row(Title='Like Father Like Son'),
 Row(Title='Rope'),
 Row(Title='Road to Hong Kong'),
 Row(Title='Shirley Valentine'),
 Row(Title='City of Joy'),
 Row(Title='AppaloosaThe'),
 Row(Title='Seven Minutes in Heaven'),
 Row(Title="Hearts of DarknessA Filmmaker's Apocalypse"),
 Row(Title='Tonight for Sure'),
 Row(Title='White HunterBlack Heart'),
 Row(Title='Sundays & Cybele'),
 Row(Title='Puppet Master'),
 Row(Title='Night Gallery'),
 Row(Title='Pet Sematary'),
 Row(Title="America's MusicGospel"),
 Row(Title='Slap Shot'),
 Row(Title='O. C. & Stiggs'),
 Row(Title='A Fish Called Wanda'),
 Row(Title='A Lesson in Love'),
 Row(Title='Brink of Life'),
 Row(Title='Betty Blue'),
 Row(Title='Hair'),
 Row(Title="National Lampoon's Christmas Vacation"),
 Row(Title='Dersu Uzala(The Hunter)'),
 Row(Title='Alice'),
 Row(Title='Fifth FloorThe'),
 Row(Title='Snow Kill'),
 Row(Title='PeopleThe'),
 Row(Title='True Grit'),
 Row(Title='Battle of MidwayThe'),
 Row(Title='Three Godfathers'),
 Row(Title='HushHushSweet Charlotte'),
 Row(Title='A Stolen Life'),
 Row(Title='Old MaidThe'),
 Row(Title='All about Eve'),
 Row(Title='FlyThe'),
 Row(Title='Quick Change'),
 Row(Title='Lair of the White WormThe'),
 Row(Title='RainbowThe'),
 Row(Title='Man Who Knew Too MuchThe'),
 Row(Title='Beauty & the Beast'),
 Row(Title='Foreign Correspondent'),
 Row(Title='HeiressThe'),
 Row(Title='Boy Who Could FlyThe'),
 Row(Title='TerroristsThe'),
 Row(Title='Wheel of Fortune'),
 Row(Title='Do the Right Thing'),
 Row(Title='Court-Martial of Jackie RobinsonThe'),
 Row(Title='Elvira Madigan'),
 Row(Title='Hurricane Smith'),
 Row(Title='Fair Game'),
 Row(Title='Rape of the SabinesThe'),
 Row(Title='Risky Business'),
 Row(Title='I Love All of You (Je Vous Aime)'),
 Row(Title='Love Songs'),
 Row(Title='Le Choix des Armes'),
 Row(Title='Choice of Arms'),
 Row(Title='March or Die'),
 Row(Title='Last MetroThe'),
 Row(Title='Jean de Florette'),
 Row(Title='Fat Man & Little Boy'),
 Row(Title='Wild at Heart'),
 Row(Title='Family Business'),
 Row(Title='Stand & Deliver'),
 Row(Title='Looker'),
 Row(Title='Fire & Rain'),
 Row(Title='Best of Candid CameraThe'),
 Row(Title='Seven Sinners'),
 Row(Title='Judgment at Nuremberg'),
 Row(Title="Minsky's Follies"),
 Row(Title='NoviceThe'),
 Row(Title='Wings of Desire'),
 Row(Title='Until the End of the World'),
 Row(Title='Castaway'),
 Row(Title="Alfred Hitchcock PresentsSorcerer's Apprentice"),
 Row(Title='Delicatessen'),
 Row(Title='Great Train RobberyThe'),
 Row(Title='Hanover Street'),
 Row(Title='Hunchback'),
 Row(Title='My Darling Clementine'),
 Row(Title='Wagon Master'),
 Row(Title='She Wore a Yellow Ribbon'),
 Row(Title='Fantasy Man'),
 Row(Title='Monster in the Closet'),
 Row(Title='Double Edge'),
 Row(Title='Network'),
 Row(Title='Chinatown'),
 Row(Title='Three Days of the Condor'),
 Row(Title='Voyage of the Damned'),
 Row(Title='Barfly'),
 Row(Title='Wait Until SpringBandini'),
 Row(Title='Life with Father'),
 Row(Title='A Guy Named Joe'),
 Row(Title='Stavisky'),
 Row(Title='Time Bandits'),
 Row(Title='ShiningThe'),
 Row(Title='Flame of Barbary Coast'),
 Row(Title='Naked TruthThe'),
 Row(Title='BroodThe'),
 Row(Title='Molly MaguiresThe'),
 Row(Title='Beverly Hills Cop'),
 Row(Title="Blind Man's Bluff"),
 Row(Title='La Dolce Vita'),
 Row(Title='After the Fox'),
 Row(Title='Man with the Golden GunThe'),
 Row(Title='Marbella'),
 Row(Title='BoboThe'),
 Row(Title='Big BandsThe'),
 Row(Title='Killer Image.'),
 Row(Title='Kandyland'),
 Row(Title='Campus Man'),
 Row(Title='Jubal'),
 Row(Title='Purple Rose of CairoThe'),
 Row(Title='Broadway Danny Rose'),
 Row(Title='Husbands & Wives'),
 Row(Title='Hannah & Her Sisters'),
 Row(Title='Hurricane'),
 Row(Title='Between Two Women'),
 Row(Title='Cannonball RunThe'),
 Row(Title='Doughnuts & Society'),
 Row(Title='Holocaust'),
 Row(Title='Meridian'),
 Row(Title='Diary of a Hitman'),
 Row(Title='Gor'),
 Row(Title='Surrender'),
 Row(Title='Places in the Heart'),
 Row(Title='Not Without My Daughter'),
 Row(Title='Heroes'),
 Row(Title='Absence of Malice'),
 Row(Title='Norma Rae'),
 Row(Title='Steel Magnolias'),
 Row(Title='BurbsThe'),
 Row(Title='Empire Strikes BackThe'),
 Row(Title='Star Wars'),
 Row(Title='Return of the Jedi'),
 Row(Title='Hear My Song'),
 Row(Title='Slightly Scarlet'),
 Row(Title='Gunfight at the OK Corral'),
 Row(Title='Range FeudThe'),
 Row(Title='Bloodsucking Pharaohs in Pittsburgh'),
 Row(Title='Roma'),
 Row(Title='China SyndromeThe'),
 Row(Title='Morning AfterThe'),
 Row(Title='Klute'),
 Row(Title='Electric HorsemanThe'),
 Row(Title='Cat Ballou'),
 Row(Title='Coming Home'),
 Row(Title='Rebecca'),
 Row(Title='Jane Eyre'),
 Row(Title='Stacey!'),
 Row(Title='Naked Obsession'),
 Row(Title='Stripped to Kill IILive Girls'),
 Row(Title='Rain KillerThe'),
 Row(Title='Valley Girl'),
 Row(Title='Silence of the LambsThe'),
 Row(Title='Stealing Home'),
 Row(Title='Napoleon & Samantha'),
 Row(Title='Five Corners'),
 Row(Title='Blackboard JungleThe'),
 Row(Title='My Left Foot'),
 Row(Title='Back to the Beach'),
 Row(Title='Painted VeilThe'),
 Row(Title='Inspiration'),
 Row(Title='Anna Christie'),
 Row(Title='Flesh & the DevilThe'),
 Row(Title='Woman of Affairs'),
 Row(Title='Anna Karenina'),
 Row(Title='Camille'),
 Row(Title='Mata Hari'),
 Row(Title='Wild Orchids'),
 Row(Title='Grand Hotel'),
 Row(Title='Susan LennoxHer Fall & Rise'),
 Row(Title='Ninotchka'),
 Row(Title='Queen Christina'),
 Row(Title='Mysterious LadyThe'),
 Row(Title='Joyless Street'),
 Row(Title='Single StandardThe'),
 Row(Title='As You Desire Me'),
 Row(Title='Romance'),
 Row(Title='A Child Is Waiting'),
 Row(Title='Tootsie'),
 Row(Title='Let It Ride'),
 Row(Title='Julius Caesar'),
 Row(Title='Nineteen Forty-One'),
 Row(Title='Jaws'),
 Row(Title='Hot Pursuit'),
 Row(Title='Triumph of the Spirit'),
 Row(Title='Brannigan'),
 Row(Title='Buffet Froid'),
 Row(Title='Salvador'),
 Row(Title='Horse SoldiersThe'),
 Row(Title='Long John Silver'),
 Row(Title='HustlerThe'),
 Row(Title='Star ChamberThe'),
 Row(Title="Clara's Heart"),
 Row(Title='Burglar'),
 Row(Title='Comic Relief'),
 Row(Title='Bloodbrothers'),
 Row(Title='Rain Man'),
 Row(Title='Masculine Feminine'),
 Row(Title='Outer LimitsThe'),
 Row(Title="Mama's Dirty Girls"),
 Row(Title='Last Ride of the Dalton GangThe'),
 Row(Title='Why Me?'),
 Row(Title='Number Seventeen'),
 Row(Title='Manhunter'),
 Row(Title='Bonfire of the VanitiesThe'),
 Row(Title='Working Girl'),
 Row(Title='Shining Through'),
 Row(Title='Slumber Party Massacre III'),
 Row(Title='Tokyo Pop'),
 Row(Title='Terminator 2'),
 Row(Title='TerminatorThe'),
 Row(Title='King Kong Lives!'),
 Row(Title='Those Daring Young Men in Their Jaunty'),
 Row(Title='At Play in the Fields of the Lord'),
 Row(Title='Crazy People'),
 Row(Title='Memoirs of an Invisible Man'),
 Row(Title='Clan of the Cave BearThe'),
 Row(Title='Final TerrorThe'),
 Row(Title='Reckless'),
 Row(Title='High Spirits'),
 Row(Title='Roxanne'),
 Row(Title='Blade Runner'),
 Row(Title='Wall Street'),
 Row(Title='Pope of Greenwich Village'),
 Row(Title='After School'),
 Row(Title='Flaming Frontiers'),
 Row(Title='Libeled Lady'),
 Row(Title='Inserts'),
 Row(Title='Blue IguanaThe'),
 Row(Title='Tender Mercies'),
 Row(Title='Nights in White Satin'),
 Row(Title='Videodrome'),
 Row(Title='Intimate Stranger'),
 Row(Title='Highlander'),
 Row(Title='Bodycount'),
 Row(Title='Tango & Cash'),
 Row(Title="There's a Girl in My Soup"),
 Row(Title='Swing Shift'),
 Row(Title='Foul Play'),
 Row(Title='Best Friends'),
 Row(Title='Butterflies Are Free'),
 Row(Title='Overboard'),
 Row(Title='Girl from PetrovkaThe'),
 Row(Title='Housesitter'),
 Row(Title='Wildcats'),
 Row(Title='Protocol'),
 Row(Title='Seems Like Old Times'),
 Row(Title='Sugarland ExpressThe'),
 Row(Title='Private Benjamin'),
 Row(Title='Deceived'),
 Row(Title='Arrowsmith'),
 Row(Title='Say Goodbye Maggie Cole'),
 Row(Title='Circus World'),
 Row(Title='Affair in Trinidad'),
 Row(Title='Lady from Shanghai'),
 Row(Title='Lady in Question'),
 Row(Title='Gilda'),
 Row(Title='Loves of CarmenThe'),
 Row(Title='Dick Tracy'),
 Row(Title='Marnie'),
 Row(Title='Hot Child in the City'),
 Row(Title='Johnny Dangerously'),
 Row(Title='Stark'),
 Row(Title='Three Strange Loves'),
 Row(Title='My Fair Lady'),
 Row(Title='UnforgivenThe'),
 Row(Title='Robin & Marian'),
 Row(Title="Children's HourThe"),
 Row(Title='RainmakerThe'),
 Row(Title='Pat & Mike'),
 Row(Title='Lion in WinterTHe'),
 Row(Title='Sea of GrassThe'),
 Row(Title="Guess Who's Coming to Dinner"),
 Row(Title='Desk Set'),
 Row(Title='Rooster Cogburn'),
 Row(Title='On Golden Pond'),
 Row(Title="Adam's Rib"),
 Row(Title='Boom Town'),
 Row(Title='Dragon Seed'),
 Row(Title='Little Women'),
 Row(Title='Philadelphia StoryThe'),
 Row(Title='Without Love'),
 Row(Title='Woman of the Year'),
 Row(Title='Juice'),
 Row(Title='Hoosiers'),
 Row(Title='Tin Men'),
 Row(Title='Last Temptation of ChristThe'),
 Row(Title='Paris Trout'),
 Row(Title='Souvenir'),
 Row(Title='A Man for All Seasons'),
 Row(Title='Knights & Emeralds'),
 Row(Title='Masque of the Red Death'),
 Row(Title="Adventures of Smilin' JackThe"),
 Row(Title='Adventures in Dinosaur City'),
 Row(Title='AllnighterThe'),
 Row(Title='Caddyshack'),
 Row(Title='Tom Sawyer'),
 Row(Title='RitaSue & Bob Too'),
 Row(Title='Hawk of Powder River'),
 Row(Title='Tempest'),
 Row(Title='Running Mates'),
 Row(Title='Prettykill'),
 Row(Title='Judge Priest'),
 Row(Title='Harvey'),
 Row(Title='If Looks Could Kill'),
 Row(Title='Raising Arizona'),
 Row(Title='Once Around'),
 Row(Title='Loulou'),
 Row(Title='World According to GarpThe'),
 Row(Title='Virus'),
 Row(Title='Northwest Passage'),
 Row(Title='Gardens of Stone'),
 Row(Title='Enemiesa Love Story'),
 Row(Title='Addams FamilyThe'),
 Row(Title='Freaks'),
 Row(Title='Necessary Roughness'),
 Row(Title='A Show of Force'),
 Row(Title='CompetitionThe'),
 Row(Title='Crossing Delancey'),
 Row(Title='State of ThingsThe'),
 Row(Title='Business As Usual'),
 Row(Title='A Touch of Class'),
 Row(Title='Women in Love.'),
 Row(Title="Salome's Last Dance"),
 Row(Title='Casino'),
 Row(Title='Smiles of a Summer Night'),
 Row(Title="New Year's Day"),
 Row(Title='Mephisto'),
 Row(Title='Easy Virtue'),
 Row(Title='Swing It Sailor!'),
 Row(Title='Strictly Business'),
 Row(Title='Blame It on Rio'),
 Row(Title='Straight to Hell'),
 Row(Title='A View to a Kill'),
 Row(Title='American Anthem'),
 Row(Title='Bedtime Story'),
 Row(Title="Courtship of Eddie's FatherThe"),
 Row(Title='Night Train to KatmanduTHe'),
 Row(Title='Port of Call'),
 Row(Title='Paper Moon'),
 Row(Title='Yellowbeard'),
 Row(Title="Adventures of Sherlock Holmes' Smarter"),
 Row(Title='Flashback'),
 Row(Title="World's Greatest LoverThe"),
 Row(Title="Killer's Kiss"),
 Row(Title='DeceiversThe'),
 Row(Title='Breathless'),
 Row(Title='Born on the Fourth of July'),
 Row(Title='Awakenings'),
 Row(Title='Annie Hall'),
 Row(Title='Manhattan'),
 Row(Title='Reds'),
 Row(Title='Crimes of the Heart'),
 Row(Title='Looking for Mr. Goodbar'),
 Row(Title='GodfatherThe'),
 Row(Title='GodfatherPt 2.The'),
 Row(Title='I WillI Will...For Now'),
 Row(Title='Play It AgainSam'),
 Row(Title='Love & Death'),
 Row(Title='Sleeper'),
 Row(Title='Fellini Satyricon'),
 Row(Title='FormulaThe'),
 Row(Title='Black Sunday'),
 Row(Title='Bobby Deerfield'),
 Row(Title='Last of the Red Hot Lovers'),
 Row(Title='Mogambo'),

In [21]:
long_titles=rdd.filter(lambda x:int(len(x[0])) > 50).collect()

In [20]:
rddColumns = ["Title"] #name of the column 



#### convert to df #############################################################
df_15_2 = spark.createDataFrame(long_titles, schema = rddColumns)
# dataframe = function(rdd to convert , schema = columns as an array)
df_15_2.show(truncate=False)

+-----------------------------------------------------------------+
|Title                                                            |
+-----------------------------------------------------------------+
|Fawlty TowersGourmet NightWaldorf Salad & The Kipper & the Corpse|
+-----------------------------------------------------------------+